### ISSUE TITLE
Forced reflow while executing JavaScript

### ISSUE THREAD

**Issue by binarious** [jsxtools/cqfill#16]
I'm seeing a lot of `Forced reflow while executing JavaScript took 34ms` in the console when adding this library.

Any hint what could be optimized?

**Comment by jonathantneal** [comment]
Would you share an example? I’m not sure how well anyone would be able to guess without seeing it.

**Comment by binarious** [comment]
I could share an example project via mail with you if you're interested. I don't have a public example project in which this could be reproduced since it seems to need some amount of DOM nodes or a special structure to occur.

**Comment by binarious** [comment]
Closing this for now as I can't reproduce it in a smaller separate project and therefore I'm unsure if the root cause really is this library.
